### ISSUE TITLE
Chapter 2. Bullet point inside an exercise

### ISSUE THREAD

**Issue by ppalagi** [elixir-europe-training/ELIXIR-TrP-FAIR-training-handbook#48]
Hello all,

in the exercise starting with: "Have a look at the slides on the [String Database (by Lars Juhl Jensen)](https://www.slideshare.net/larsjuhljensen/the-string-database) on Slideshare. Imagine the slides were downloadable in pptx format.", the following 3 bullet points should be inside the box of the exercise (not outside).

Does anyone have the magic Markdown answer? Thanks.

**Comment by GeertvanGeest** [comment]
Missing indentation:

https://github.com/elixir-europe-training/ELIXIR-TrP-FAIR-training-handbook/blob/47efa9c268f74c2808204cc8e5a59ddbd5d34765/docs/chapters/chapter_02.md?plain=1#L91-L95

**Comment by GeertvanGeest** [comment]
This should fix it:

https://github.com/elixir-europe-training/ELIXIR-TrP-FAIR-training-handbook/blob/d0ea2828573987b6df9ea1f0b48ec76c2d26cc02/docs/chapters/chapter_02.md?plain=1#L89-L95

**Comment by GeertvanGeest** [comment]
And fixed
